<?php
/**
 * Created by PhpStorm.
 * User: devert
 * Date: 4/17/20
 * Time: 11:37 PM
 */

namespace App\Services\Clients\Providers\ExpressUnion;


use App\Services\Objects\Account;

class ExpressUnionCashinClient extends ExpressUnionClient
{
    public function buy(Account $account): bool
    {
        parent::buy($account); // TODO: Change the autogenerated stub
    }
}