# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8084/ping

###

POST http://localhost:8084/execute
Content-Type: application/json

{
  "service_code": "CORORANGEWEBPAY",
  "destination": "653754334",
  "external_id": "875455wewrac",
  "amount": "1",
  "callback_url": "https://webhook.site/ee3e39b8-98df-46d7-98b3-848c620a894b"
}

### MOMO CASHIN

POST http://localhost:8084/execute
Content-Type: application/json

{
  "service_code": "CORMTNIN",
  "destination": "653754334",
  "external_id": "fdafda",
  "amount": "10",
  "callback_url": "https://webhook.site/ee3e39b8-98df-46d7-98b3-848c620a894b"
}

###
